name: "devclean’s explanation helped me"
description: "devclean reduced your hesitation"
title: "Explanation helped: <directory name>"
labels: ["positive-feedback", "trust"]
body:
  - type: markdown
    attributes:
      value: |
        This feedback helps us understand what builds trust.

  - type: input
    id: directory
    attributes:
      label: Directory name

  - type: textarea
    id: helpful_part
    attributes:
      label: What part of the explanation helped most?

  - type: dropdown
    id: action
    attributes:
      label: What did you do afterward?
      options:
        - Deleted the directory
        - Deleted part of it
        - Did not delete it, but felt more confident

  - type: textarea
    id: did_right
    attributes:
      label: What did devclean do right?

  - type: markdown
    attributes:
      value: |
        ### Maintainer note

        These templates intentionally avoid feature-request framing.

        We prioritize:
        1. Real hesitation and fear of deletion
        2. Incorrect or missing detection rules
        3. Explanations that fail to build trust