name: "devclean’s analysis did not convince me"
description: "devclean produced a result, but you did not trust it"
title: "Not convinced by analysis: <directory name>"
labels: ["trust", "explanation"]
body:
  - type: markdown
    attributes:
      value: |
        This template helps us understand where devclean failed to build trust.

  - type: textarea
    id: output
    attributes:
      label: devclean output
      render: text

  - type: input
    id: directory
    attributes:
      label: Directory in question

  - type: textarea
    id: concern
    attributes:
      label: Why did this not feel trustworthy?

  - type: textarea
    id: missing_info
    attributes:
      label: What additional information would help?

  - type: markdown
    attributes:
      value: |
        ### Maintainer note

        These templates intentionally avoid feature-request framing.

        We prioritize:
        1. Real hesitation and fear of deletion
        2. Incorrect or missing detection rules
        3. Explanations that fail to build trust